[package]

name = "piston3d-gfx_voxel"
version = "0.0.5"
authors = [
    "Ty Overby <ty@pre-alpha.com>",
    "eddyb",
    "Sven Nilsen <bvssvni@gmail.com>"
]
keywords = ["gfx", "3d", "voxel", "piston"]
description = "A voxel rendering library on top of Gfx"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/gfx_voxel.git"
homepage = "https://github.com/pistondevelopers/gfx_voxel"

[lib]

name = "gfx_voxel"

[dependencies.piston-gfx_texture]
git = "https://github.com/PistonDevelopers/gfx_texture"
#version = "0.0.0"

[dependencies.image]
git = "https://github.com/PistonDevelopers/image"
#version = "0.0.0"

[dependencies.array]
git = "https://github.com/PistonDevelopers/array"
#version = "0.0.0"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs"
#version = "0.0.0"
