[package]

name = "gfx_voxel"
version = "0.0.1"
authors = [
    "Ty Overby <ty@pre-alpha.com>",
    "eddyb",
    "Sven Nilsen <bvssvni@gmail.com>"
]
tags = []

[lib]

name = "gfx_voxel"
path = "src/lib.rs"

[dependencies.image]

git = "https://github.com/PistonDevelopers/image"

[dependencies.vecmath]

git = "https://github.com/PistonDevelopers/vecmath"

[dependencies.gfx]

git = "https://github.com/gfx-rs/gfx-rs"
